-- CreateTable
CREATE TABLE `Bill` (
    `id` VARCHAR(191) NOT NULL,
    `transactionId` VARCHAR(191) NOT NULL,
    `transactionDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `company` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `phone` VARCHAR(191) NOT NULL,
    `companyAddress` VARCHAR(191) NOT NULL,
    `state` VARCHAR(191) NOT NULL,
    `pin` VARCHAR(191) NOT NULL,
    `gst` VARCHAR(191) NOT NULL,
    `paymentMode` VARCHAR(191) NOT NULL DEFAULT 'Razorpay Wallet',
    `productName` VARCHAR(191) NOT NULL,
    `skuId` VARCHAR(191) NOT NULL,
    `quantity` INTEGER NOT NULL,
    `price` DOUBLE NOT NULL,
    `currency` ENUM('USD', 'INR') NOT NULL,
    `shippingCharge` DOUBLE NOT NULL,
    `taxPercent` DOUBLE NOT NULL,
    `payableAmount` DOUBLE NOT NULL,
    `invoiceUrl` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Bill_transactionId_key`(`transactionId`),
    INDEX `Bill_transactionId_idx`(`transactionId`),
    INDEX `Bill_company_idx`(`company`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
