-- AlterTable
ALTER TABLE `order` ADD COLUMN `status` ENUM('IN_PROGRESS', 'SHIPPED', 'RTO') NOT NULL DEFAULT 'IN_PROGRESS';

-- AlterTable
ALTER TABLE `settings` MODIFY `companyPan` VARCHAR(191) NOT NULL DEFAULT 'CANPJ8390R',
    MODIFY `companyGst` VARCHAR(191) NOT NULL DEFAULT '08CANPJ3390R1ZT';

-- AlterTable
ALTER TABLE `user` ADD COLUMN `company` VARCHAR(191) NULL,
    ADD COLUMN `companyAddress` VARCHAR(191) NULL,
    ADD COLUMN `email` VARCHAR(191) NULL,
    ADD COLUMN `gst` VARCHAR(191) NULL,
    ADD COLUMN `phone` VARCHAR(191) NULL,
    ADD COLUMN `pin` VARCHAR(191) NULL,
    ADD COLUMN `state` VARCHAR(191) NULL;
